### ISSUE TITLE
Poetry in RTD

### ISSUE THREAD

**Issue by alecandido** [N3PDF/workflows#15]
As done for [EKO](https://github.com/NNPDF/eko/blob/633fbb48f6a5d85b49757f7417c1c0ca4b5f16ff/.readthedocs.yaml#L9-L14) we should use Poetry to install deps on readthedocs as well.

The current solution was just a temporary hack.

Here the official guide: https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

NOTE: I'm putting it here, but of course is intended for all the other repos: yadism, pineko, pinefarm, ...

**Comment by felixhekhorn** [comment]
banana: https://github.com/N3PDF/banana/commit/0c97d3d7f569be1ffdd84cca4f609dab32f40093

**Comment by felixhekhorn** [comment]
pinefarm: https://github.com/NNPDF/pinefarm/commit/193d7ac063e457dc9bcc137559de2898ae9d8322

**Comment by felixhekhorn** [comment]
yadism: https://github.com/NNPDF/yadism/commit/3be2d772680db40ce3ba1457b8d781feb6e1855a

**Comment by felixhekhorn** [comment]
pineko: https://github.com/NNPDF/pineko/commit/a17f1af3ddfdd351c46d5ff8fb9501f3fbf8fe86

**Comment by felixhekhorn** [comment]
pineappl is under maturin so out of scope ... and then that's it, right?

**Comment by alecandido** [comment]
Yes, thank you very much :D
