### ISSUE TITLE
Outdated PyPI workflow

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/workflows#2]
Looking here https://github.com/N3PDF/pineko/actions/runs/2874826710 we got

> publish / 📦 PyPI (🐍 3.8): # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1
> You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

since we're on it: shall we increase the default Python version?

**Comment by felixhekhorn** [comment]
I guess this is closed by https://github.com/N3PDF/workflows/commit/a96337154b082e7d521405a2d24d1a1af4627e72 correct?

**Comment by AleCandido** [comment]
Yes, I found this thanks to `pineko` failing releasing.
