### ISSUE TITLE
Add git and curl to the lhapdf container

### ISSUE THREAD

**Issue by Radonirinaunimi** [N3PDF/workflows#8]
@AleCandido Could you please add `git>=2.18` to the lhapdf container? Currently `checkout@v2` uses the REST API (https://github.com/NNPDF/nnusf/actions/runs/3197091119/jobs/5219862852) to download the `tar`. Also, the installation of poetry fails because `curl` is not installed.

**Comment by AleCandido** [comment]
The reason why `curl` is not present is that I'm using a multi-stage build, just retaining a minimal environment:
https://github.com/N3PDF/workflows/blob/6e415c2b5ebd4daa51b6db454f65b5f1b8ac1e62/containers/lhapdf/Containerfile#L24

However, we can always install in the container at build time, and we only need `apt install curl`, like in the previous stage:
https://github.com/N3PDF/workflows/blob/6e415c2b5ebd4daa51b6db454f65b5f1b8ac1e62/containers/lhapdf/Containerfile#L4-L5

For Git we can do the same. Unless the image is based on a (very) old distribution, and I don't think so :)

**Comment by AleCandido** [comment]
This should be solved by https://github.com/N3PDF/workflows/pkgs/container/lhapdf/45025179?tag=0.1.2

Please, check it @Radonirinaunimi, and close the issue if this is the case :)
